name: supporting
channels:
  - omnia
  - egilliesix
dependencies:
  - python=2.7
  - nomkl
  - pymol
  - numpy
  - libglu
  - pip:
      - apscheduler
      - gunicorn
      - flask
      - cclib==1.4.1