package:
  name: esigen
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

about:
  home: https://github.com/insilichem/esigen
  summary: Generate Supporting Information reports for Comp Chem studies.

source:
  path: ../../

requirements:
  build:
    - python

  run:
    - python
    - nomkl
    - numpy
    - pymol     # [py27 and linux]
    - libglu    # [py27 and linux]
    - glew      # [py27 and linux]

test:
  imports:
    - esigen



